version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--requirepass", "toor", "--appendonly", "yes"]
    networks:
      - app-network
    ports:
      - 6379:6379
    restart: on-failure
  goapp:
    build: .
    command: ["./app","api"]
    container_name: goapp
    networks:
      - app-network
    ports:
      - 1323:1323
    restart: on-failure
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus
    networks:
      - app-network
    volumes:
      - ./yaml/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - goapp

networks:
  app-network:
    driver: bridge